//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.H_D.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RexTester {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RexTester() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("J.H_D.Data.Resources.RexTester", typeof(RexTester).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 39.
        /// </summary>
        internal static string Ada {
            get {
                return ResourceManager.GetString("Ada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 38.
        /// </summary>
        internal static string Bash {
            get {
                return ResourceManager.GetString("Bash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 44.
        /// </summary>
        internal static string Brainfuck {
            get {
                return ResourceManager.GetString("Brainfuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.
        /// </summary>
        internal static string C_ {
            get {
                return ResourceManager.GetString("C#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 27.
        /// </summary>
        internal static string C____clang_ {
            get {
                return ResourceManager.GetString("C++ (clang)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.
        /// </summary>
        internal static string C____gcc_ {
            get {
                return ResourceManager.GetString("C++ (gcc)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 28.
        /// </summary>
        internal static string C____vc___ {
            get {
                return ResourceManager.GetString("C++ (vc++)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 26.
        /// </summary>
        internal static string C__clang_ {
            get {
                return ResourceManager.GetString("C (clang)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.
        /// </summary>
        internal static string C__gcc_ {
            get {
                return ResourceManager.GetString("C (gcc)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 29.
        /// </summary>
        internal static string C__vc_ {
            get {
                return ResourceManager.GetString("C (vc)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 47.
        /// </summary>
        internal static string Clojure {
            get {
                return ResourceManager.GetString("Clojure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 41.
        /// </summary>
        internal static string Elixir {
            get {
                return ResourceManager.GetString("Elixir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 40.
        /// </summary>
        internal static string Erlang {
            get {
                return ResourceManager.GetString("Erlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.
        /// </summary>
        internal static string F_ {
            get {
                return ResourceManager.GetString("F#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 45.
        /// </summary>
        internal static string Fortran {
            get {
                return ResourceManager.GetString("Fortran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 20.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 11.
        /// </summary>
        internal static string Haskell {
            get {
                return ResourceManager.GetString("Haskell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.
        /// </summary>
        internal static string Java {
            get {
                return ResourceManager.GetString("Java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 17.
        /// </summary>
        internal static string Javascript {
            get {
                return ResourceManager.GetString("Javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 43.
        /// </summary>
        internal static string Kotlin {
            get {
                return ResourceManager.GetString("Kotlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 18.
        /// </summary>
        internal static string Lisp {
            get {
                return ResourceManager.GetString("Lisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 14.
        /// </summary>
        internal static string Lua {
            get {
                return ResourceManager.GetString("Lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 33.
        /// </summary>
        internal static string MySQL {
            get {
                return ResourceManager.GetString("MySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 15.
        /// </summary>
        internal static string Nasm {
            get {
                return ResourceManager.GetString("Nasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 23.
        /// </summary>
        internal static string Node_js {
            get {
                return ResourceManager.GetString("Node.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 10.
        /// </summary>
        internal static string Objective_C {
            get {
                return ResourceManager.GetString("Objective-C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 42.
        /// </summary>
        internal static string Ocaml {
            get {
                return ResourceManager.GetString("Ocaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 25.
        /// </summary>
        internal static string Octave {
            get {
                return ResourceManager.GetString("Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 35.
        /// </summary>
        internal static string Oracle {
            get {
                return ResourceManager.GetString("Oracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9.
        /// </summary>
        internal static string Pascal {
            get {
                return ResourceManager.GetString("Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 13.
        /// </summary>
        internal static string Perl {
            get {
                return ResourceManager.GetString("Perl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.
        /// </summary>
        internal static string Php {
            get {
                return ResourceManager.GetString("Php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 34.
        /// </summary>
        internal static string PostgreSQL {
            get {
                return ResourceManager.GetString("PostgreSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 19.
        /// </summary>
        internal static string Prolog {
            get {
                return ResourceManager.GetString("Prolog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.
        /// </summary>
        internal static string Python {
            get {
                return ResourceManager.GetString("Python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 24.
        /// </summary>
        internal static string Python_3 {
            get {
                return ResourceManager.GetString("Python 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 31.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 12.
        /// </summary>
        internal static string Ruby {
            get {
                return ResourceManager.GetString("Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 46.
        /// </summary>
        internal static string Rust {
            get {
                return ResourceManager.GetString("Rust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 21.
        /// </summary>
        internal static string Scala {
            get {
                return ResourceManager.GetString("Scala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 22.
        /// </summary>
        internal static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 16.
        /// </summary>
        internal static string Sql_Server {
            get {
                return ResourceManager.GetString("Sql Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 37.
        /// </summary>
        internal static string Swift {
            get {
                return ResourceManager.GetString("Swift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 32.
        /// </summary>
        internal static string Tcl {
            get {
                return ResourceManager.GetString("Tcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2.
        /// </summary>
        internal static string VB_NET {
            get {
                return ResourceManager.GetString("VB.NET", resourceCulture);
            }
        }
    }
}
