J::H_D::Tools::Utilities
const int J.H_D.Tools.Utilities.DiscordMessageCharacterLimit
const int J.H_D.Tools.Utilities.DiscordEmbedMessageCharacterLimit
static void J.H_D.Tools.Utilities.CheckDir(string Path)
Check if a directory exist, if it doesn't, create it
Path The path to test
static void J.H_D.Tools.Utilities.DeleteDirectoryContent(string path)
Delete all the content inside a directory
path The path to the directory to delete content
static string J.H_D.Tools.Utilities.DiscordFriendly(string OriginalString, bool Embed=false)
Make the message Discord-friendly, removing the exceed of characters
OriginalString The string to test A Discord-friendly message
static bool J.H_D.Tools.Utilities.IsChannelNsfw(ICommandContext Context)
Check if a channel is NSFW
Context A ICommandContext True if the channel is NSFW
Referenced by J.H_D.Modules.BooruModule.ProccessInfosResultAsync, J.H_D.Modules.BooruModule.ProccessResultAsync.
static string J.H_D.Tools.Utilities.RotateString(string OriginalString)
Rotate a string upside-down
OriginalString The string to rotate The rotated string
Referenced by J.H_D.Modules.CommunicationModule.RotateThenRespondAsync.
static string J.H_D.Tools.Utilities.Clarify(string WebString)
Make a HTML text reading-friendly
WebString A HTML text The text human-friendly
static string J.H_D.Tools.Utilities.MakeArgs(string[] Args)
Appends multiple strings into one
Args
Referenced by J.H_D.Modules.CommunicationModule.ClarifyThenRespondAsync.
static string J.H_D.Tools.Utilities.MakeQueryArgs(string[] Args)
Text escpae string to prevent bad requests
Args
static string J.H_D.Tools.Utilities.GetPlainTextFromHtml(string htmlString)
Get plain text from HTML's one using Regex
htmlString An HTML string The plain text of the HTML string
Referenced by J.H_D.Modules.CommunicationModule.ClarifyThenRespondAsync.
static Dictionary<string, string> J.H_D.Tools.Utilities.GetEmbedAttributesValues< T >(T EmbedableData, List< string > NeededValues)
Return all the values asked in the list from the EmbedableAttribute of an object
T The class of the EmbedableData object EmbedableData The embedableData object NeededValues A list of values of tags you want
References J.H_D.Data.EmbedableAttribute.Name.
static string J.H_D.Tools.Utilities.GetEmbedAttributeValue< T >(T EmbedableData, string NeededValue)
Return the value asked from the Embedable data attribute
T The class of the EmbedableData object EmbedableData The embedableData object NeededValue The name of the Embedable Attribute field you want
References J.H_D.Data.EmbedableAttribute.Name.
static Stream J.H_D.Tools.Utilities.GetStreamFromUrl(string Url)
Get memory stream from an Url
Url The url to get fetch the data from A MemoryStream with the url data
static string J.H_D.Tools.Utilities.StandardUppercase(string ToUp)